In [3]:
x = [1,2,3]
y =[2,3,4]
ans = []
for a,b in zip(x,y):
    v = a + b
    ans.append(v)
print(ans)

[3, 5, 7]


In [ ]:
x = [[1,2], [3,4]]
y =[[2,3], [4,5]]




number processing library for python - numpy
- array : it is a list of homogenous elements

In [4]:
import numpy as np

In [7]:
x = np.array([1,2,3])
y = np.array([2,3,4])
print(x,'+',y,'=',x+y)
print(x,'-',y,'=',x-y)
print(x,'*',y,'=',x*y)
print(x,'/',y,'=',x/y)
print(x,'//',y,'=',x//y)

[1 2 3] + [2 3 4] = [3 5 7]
[1 2 3] - [2 3 4] = [-1 -1 -1]
[1 2 3] * [2 3 4] = [ 2  6 12]
[1 2 3] / [2 3 4] = [0.5        0.66666667 0.75      ]
[1 2 3] // [2 3 4] = [0 0 0]


matrices are
- 1D array
- 2D array
- 3D arr
- 4D array
- nD array

In [10]:
# one dimnsion matrix
x = np.array([1,2,3])
print(x, type(x), x.shape, x.ndim)
# two dimension matrix
x2 =np.array([[1,2],[3,4]])
print(x2, type(x2), x2.shape, x2.ndim)

[1 2 3] <class 'numpy.ndarray'> (3,) 1
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 2


In [9]:
#3 dimension matrix
x3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3, x3.shape, x3.ndim, x3.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2) 3 8


In [12]:
# 6 * 6 matrix
x4 =np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18],
    [19,20,21,22,23,24],
    [25,26,27,28,29,30],
    [31,32,33,34,35,36],
])
print(x4.shape, x4.ndim, x4.size)

(6, 6) 2 36


matrix generation in numpy
- array() # basic
- arange() # range of values with  gap
- linspace() # range of values with equal gap 
- logspace() # range of values with equal gap in log scale
- zeros() # array with all zeros
- ones() # array with all ones
- eye() # identity matrix
- diag() # diagonal matrix
- random.rand() #random matrix of given shape from 0 to 1
- random.randn() # random matrix of given shape from -1 to 1
- random.randint() # random matrix of given shape from given range


In [16]:
# arange() function
x = np.arange(10)
print(x)
x1 = np.arange(-10,11,.5)
print(x1)
x2 = np.arange(-np.pi, np.pi, 2)
print(x2)
x3 = np.arange(1, 15, 2)
print(x3)

[0 1 2 3 4 5 6 7 8 9]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5]
[-3.14159265 -1.14159265  0.85840735  2.85840735]
[ 1  3  5  7  9 11 13]


In [19]:
x = np.linspace(0, 10 ,10)
print(x)
x1 = np.linspace(0, 500, 100)
print(x1)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[  0.           5.05050505  10.1010101   15.15151515  20.2020202
  25.25252525  30.3030303   35.35353535  40.4040404   45.45454545
  50.50505051  55.55555556  60.60606061  65.65656566  70.70707071
  75.75757576  80.80808081  85.85858586  90.90909091  95.95959596
 101.01010101 106.06060606 111.11111111 116.16161616 121.21212121
 126.26262626 131.31313131 136.36363636 141.41414141 146.46464646
 151.51515152 156.56565657 161.61616162 166.66666667 171.71717172
 176.76767677 181.81818182 186.86868687 191.91919192 196.96969697
 202.02020202 207.07070707 212.12121212 217.17171717 222.22222222
 227.27272727 232.32323232 237.37373737 242.42424242 247.47474747
 252.52525253 257.57575758 262.62626263 267.67676768 272.72727273
 277.77777778 282.82828283 287.87878788 292.92929293 297.97979798
 303.03030303 308.08080808 313.13131313 318.18181818 323.23232323
 328.28282828 333.33

In [20]:
z = np.zeros(10)
print(z)
z1 = np.zeros((2,3))
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
o = np.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
e = np.eye(5,dtype=int)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [26]:
np.random.rand(3,3)

array([[0.23628954, 0.2699131 , 0.90940394],
       [0.09388586, 0.85229048, 0.02173366],
       [0.14946062, 0.79702113, 0.02823907]])

In [27]:
np.random.randn(3,3)

array([[-1.20294601,  1.49712687, -1.85278039],
       [-0.9233456 ,  0.3455744 ,  0.36644545],
       [-0.41909283, -0.38309973, -1.25791293]])

In [28]:
np.random.randint(-10, 10, (5,5))

array([[-5,  0, -4,  2, -6],
       [ 1,  7,  4,  3,  0],
       [-3, -5, -6,  7, -8],
       [ 5, -8, -6, -6,  6],
       [-9,  1,  5, -5, -4]])

matrix operations