In [3]:
x = [1,2,3]
y =[2,3,4]
ans = []
for a,b in zip(x,y):
    v = a + b
    ans.append(v)
print(ans)

[3, 5, 7]


In [ ]:
x = [[1,2], [3,4]]
y =[[2,3], [4,5]]




number processing library for python - numpy
- array : it is a list of homogenous elements

In [6]:
import numpy as np

In [7]:
x = np.array([1,2,3])
y = np.array([2,3,4])
print(x,'+',y,'=',x+y)
print(x,'-',y,'=',x-y)
print(x,'*',y,'=',x*y)
print(x,'/',y,'=',x/y)
print(x,'//',y,'=',x//y)

[1 2 3] + [2 3 4] = [3 5 7]
[1 2 3] - [2 3 4] = [-1 -1 -1]
[1 2 3] * [2 3 4] = [ 2  6 12]
[1 2 3] / [2 3 4] = [0.5        0.66666667 0.75      ]
[1 2 3] // [2 3 4] = [0 0 0]


matrices are
- 1D array
- 2D array
- 3D arr
- 4D array
- nD array

In [10]:
# one dimnsion matrix
x = np.array([1,2,3])
print(x, type(x), x.shape, x.ndim)
# two dimension matrix
x2 =np.array([[1,2],[3,4]])
print(x2, type(x2), x2.shape, x2.ndim)

[1 2 3] <class 'numpy.ndarray'> (3,) 1
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 2


In [9]:
#3 dimension matrix
x3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3, x3.shape, x3.ndim, x3.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2) 3 8


In [12]:
# 6 * 6 matrix
x4 =np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18],
    [19,20,21,22,23,24],
    [25,26,27,28,29,30],
    [31,32,33,34,35,36],
])
print(x4.shape, x4.ndim, x4.size)

(6, 6) 2 36


matrix generation in numpy
- array() # basic
- arange() # range of values with  gap
- linspace() # range of values with equal gap 
- logspace() # range of values with equal gap in log scale
- zeros() # array with all zeros
- ones() # array with all ones
- eye() # identity matrix
- diag() # diagonal matrix
- random.rand() #random matrix of given shape from 0 to 1
- random.randn() # random matrix of given shape from -1 to 1
- random.randint() # random matrix of given shape from given range


In [16]:
# arange() function
x = np.arange(10)
print(x)
x1 = np.arange(-10,11,.5)
print(x1)
x2 = np.arange(-np.pi, np.pi, 2)
print(x2)
x3 = np.arange(1, 15, 2)
print(x3)

[0 1 2 3 4 5 6 7 8 9]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5]
[-3.14159265 -1.14159265  0.85840735  2.85840735]
[ 1  3  5  7  9 11 13]


In [19]:
x = np.linspace(0, 10 ,10)
print(x)
x1 = np.linspace(0, 500, 100)
print(x1)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[  0.           5.05050505  10.1010101   15.15151515  20.2020202
  25.25252525  30.3030303   35.35353535  40.4040404   45.45454545
  50.50505051  55.55555556  60.60606061  65.65656566  70.70707071
  75.75757576  80.80808081  85.85858586  90.90909091  95.95959596
 101.01010101 106.06060606 111.11111111 116.16161616 121.21212121
 126.26262626 131.31313131 136.36363636 141.41414141 146.46464646
 151.51515152 156.56565657 161.61616162 166.66666667 171.71717172
 176.76767677 181.81818182 186.86868687 191.91919192 196.96969697
 202.02020202 207.07070707 212.12121212 217.17171717 222.22222222
 227.27272727 232.32323232 237.37373737 242.42424242 247.47474747
 252.52525253 257.57575758 262.62626263 267.67676768 272.72727273
 277.77777778 282.82828283 287.87878788 292.92929293 297.97979798
 303.03030303 308.08080808 313.13131313 318.18181818 323.23232323
 328.28282828 333.33

In [20]:
z = np.zeros(10)
print(z)
z1 = np.zeros((2,3))
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
o = np.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
e = np.eye(5,dtype=int)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [26]:
np.random.rand(3,3)

array([[0.23628954, 0.2699131 , 0.90940394],
       [0.09388586, 0.85229048, 0.02173366],
       [0.14946062, 0.79702113, 0.02823907]])

In [27]:
np.random.randn(3,3)

array([[-1.20294601,  1.49712687, -1.85278039],
       [-0.9233456 ,  0.3455744 ,  0.36644545],
       [-0.41909283, -0.38309973, -1.25791293]])

In [28]:
np.random.randint(-10, 10, (5,5))

array([[-5,  0, -4,  2, -6],
       [ 1,  7,  4,  3,  0],
       [-3, -5, -6,  7, -8],
       [ 5, -8, -6, -6,  6],
       [-9,  1,  5, -5, -4]])

matrix operations
##### basic maths
- +, -, *,/,%,//,**
- dot() #matrix multiplication 
##### basic stasticstics
- sum() # sum of all elements
- min() #minimum a

In [7]:
x = np.random.randint(1,100,(4 ,6))
print(x)

[[58 50 33 12 83 47]
 [43 77 79 90 21 93]
 [62 20  2 64 80 53]
 [43 15 12 93  9 56]]


In [10]:
# sum of all values
total = x.sum() #or np.sum()
print(total)
# sum of each column 
col_total = x.sum(axis=0)
print(col_total)
# sum of each row
row_total = x.sum(axis=1)
print(row_total)

1195
[206 162 126 259 193 249]
[283 403 281 228]


In [11]:
x.mean()

49.791666666666664

In [17]:
#median
print(np.median(x))
#most common value 

51.5


In [18]:
np.sin(10)

-0.5440211108893698

In [19]:
np.sin(45)

0.8509035245341184

In [20]:
np.sin(x)

array([[ 0.99287265, -0.26237485,  0.99991186, -0.53657292,  0.96836446,
         0.12357312],
       [-0.83177474,  0.99952016, -0.44411267,  0.89399666,  0.83665564,
        -0.94828214],
       [-0.7391807 ,  0.91294525,  0.90929743,  0.92002604, -0.99388865,
         0.39592515],
       [-0.83177474,  0.65028784, -0.53657292, -0.94828214,  0.41211849,
        -0.521551  ]])

In [22]:
x.prod() #product of all values

1627389952

In [24]:
#determinant
x = np.array(([1,2],[3,4]))
np.linalg.det(x)

-2.0000000000000004

In [30]:
y = np.random.randint(0, 10, (5,5))
print(y)
print('checking if there is no zeros in the matrix')
print(np.all(y)) #or y.all()

[[3 0 4 0 3]
 [6 8 2 0 5]
 [9 5 3 0 6]
 [4 2 2 2 1]
 [9 7 1 1 3]]
checking if there is no zeros in the matrix
False


In [32]:
z = np.random.choice([0,1,0,0], (3,3))
print(z)
print('checking if there is at least one +/- value in the matrix')
print(z.any())

[[0 1 0]
 [0 0 0]
 [0 0 0]]
checking if there is at least one +/- value in the matrix
True


In [39]:
x = np.random.randint(1, 10, (4,4))
print('shape', x.shape)
print('x')
print(x)
x = x.T #transpose
print('x transposed')
print(x)
x = x.flatten()
print('x flattened')
print(x)

shape (4, 4)
x
[[6 8 2 2]
 [4 7 9 6]
 [4 1 9 1]
 [6 1 9 1]]
x transposed
[[6 4 4 6]
 [8 7 1 1]
 [2 9 9 9]
 [2 6 1 1]]
x flattened
[6 4 4 6 8 7 1 1 2 9 9 9 2 6 1 1]


In [40]:
x.reshape(8,2)


array([[6, 4],
       [4, 6],
       [8, 7],
       [1, 1],
       [2, 9],
       [9, 9],
       [2, 6],
       [1, 1]])

In [41]:
x.reshape(1,16)

array([[6, 4, 4, 6, 8, 7, 1, 1, 2, 9, 9, 9, 2, 6, 1, 1]])

# slicing and filtering

In [49]:
y = np.random.randint(1, 10, (6,6))
print(y.ndim, 'dimension')
print(y.size, 'elements')
print(y)
print('first row',y[0])
print('last row',y[-1])
print('first 3 rows\n',y[-2:])
#slicing for 2d
# arr[row, col]
print('first column\n',y[:,-0])
print('first column\n',y[:, -1])
print('first column\n',y[:,:3])
print('first column\n',y[-2:])

2 dimension
36 elements
[[4 7 3 3 6 5]
 [3 6 1 1 8 9]
 [3 2 6 4 7 9]
 [8 6 8 2 7 4]
 [2 8 3 3 8 5]
 [7 5 7 3 9 5]]
first row [4 7 3 3 6 5]
last row [7 5 7 3 9 5]
first 3 rows
 [[2 8 3 3 8 5]
 [7 5 7 3 9 5]]
first column
 [4 3 3 8 2 7]
first column
 [5 9 9 4 5 5]
first column
 [[4 7 3]
 [3 6 1]
 [3 2 6]
 [8 6 8]
 [2 8 3]
 [7 5 7]]
first column
 [[2 8 3 3 8 5]
 [7 5 7 3 9 5]]


In [51]:
#slicing for 2d object
# arr[row, col]
print('first column\n',y[:-0])
print('last column\n',y[:,-1])
print('first 3 column\n',y[:,:3])
print('last 2 column\n',y[:,-2:])

first column
 []
last column
 [5 9 9 4 5 5]
first 3 column
 [[4 7 3]
 [3 6 1]
 [3 2 6]
 [8 6 8]
 [2 8 3]
 [7 5 7]]
last 2 column
 [[6 5]
 [8 9]
 [7 9]
 [7 4]
 [8 5]
 [9 5]]


In [52]:
y > 5 #boolean filter

array([[False,  True, False, False,  True, False],
       [False,  True, False, False,  True,  True],
       [False, False,  True, False,  True,  True],
       [ True,  True,  True, False,  True, False],
       [False,  True, False, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [54]:
y[y > 5] #using boolean filter

array([7, 6, 6, 8, 9, 6, 7, 9, 8, 6, 8, 7, 8, 8, 7, 7, 9])

In [55]:
y[y < 3]

array([1, 1, 2, 2, 2])

In [57]:
y[(y>=3) & (y<=5)] #3 <= y <= 5

array([4, 3, 3, 5, 3, 3, 4, 4, 3, 3, 5, 5, 3, 5])